package Interface;

import AnalisadorLexico.Classes;
import AnalisadorLexico.Constants;
import AnalisadorLexico.Lexico;
import AnalisadorLexico.LexicalError;
import AnalisadorLexico.Token;
import Persistencia.CarregadorArquivos;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.FileWriter;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.DefaultEditorKit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Micro
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.setTitle("Compilador Linguagem 2020.1");
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/32/compile-icon.png")).getImage());
        adicionaAtalhos();
    }

    private void adicionaAtalhos() {
        JPanel contentPane = (JPanel) this.getContentPane();
        InputMap iMap = contentPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap aMap = contentPane.getActionMap();

        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_N, InputEvent.CTRL_MASK), "Ctrl + n");
        aMap.put("Ctrl + n", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jButton4ActionPerformed(e);
            }
        });

        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_O, InputEvent.CTRL_MASK), "Ctrl + o");
        aMap.put("Ctrl + o", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jButton7ActionPerformed(e);
            }
        });

        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_MASK), "Ctrl + s");
        aMap.put("Ctrl + s", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jButton9ActionPerformed(e);
            }
        });

        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F9, 0), "F9");
        aMap.put("F9", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jButton13ActionPerformed(e);
            }
        });

        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0), "F1");
        aMap.put("F1", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jButton12ActionPerformed(e);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rolagem1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton(new DefaultEditorKit.CopyAction());
        jButton11 = new javax.swing.JButton(new DefaultEditorKit.PasteAction());
        jButton10 = new javax.swing.JButton(new DefaultEditorKit.CutAction());
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Rolagem2 = new javax.swing.JScrollPane();
        AreaMensagens = new javax.swing.JTextArea();
        Painel2 = new javax.swing.JPanel();
        AreaStatus = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 900, 600));
        setMinimumSize(new java.awt.Dimension(920, 650));
        setSize(new java.awt.Dimension(900, 650));

        Rolagem1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Rolagem1.setToolTipText("");
        Rolagem1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        Rolagem1.setAutoscrolls(true);
        Rolagem1.setMinimumSize(new java.awt.Dimension(900, 400));
        Rolagem1.setPreferredSize(new java.awt.Dimension(900, 400));
        Rolagem1.setSize(new java.awt.Dimension(900, 400));

        AreaTexto.setColumns(20);
        AreaTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AreaTexto.setMinimumSize(new java.awt.Dimension(900, 400));
        AreaTexto.setSize(new java.awt.Dimension(900, 400));
        Rolagem1.setViewportView(AreaTexto);
        AreaTexto.setBorder(new NumeredBorder());

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 70));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.setLayout(new java.awt.GridLayout(1,0,0,0));

        jButton4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/32/Novo.png"))); // NOI18N
        jButton4.setText("Novo [ctrl + n]");
        jButton4.setAlignmentY(0.0F);
        jButton4.setBorderPainted(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton4.setMaximumSize(new java.awt.Dimension(110, 70));
        jButton4.setMinimumSize(new java.awt.Dimension(110, 70));
        jButton4.setPreferredSize(new java.awt.Dimension(108, 70));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton7.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/32/Abrir.png"))); // NOI18N
        jButton7.setText("Abrir [ctrl + o]");
        jButton7.setBorderPainted(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.setPreferredSize(new java.awt.Dimension(108, 70));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/32/Floppy-disk-icon.png"))); // NOI18N
        jButton9.setText("Salvar [ctrl + s]");
        jButton9.setToolTipText("");
        jButton9.setBorderPainted(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton9.setPreferredSize(new java.awt.Dimension(116, 70));
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);

        jButton8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/32/copy-icon-1.png"))); // NOI18N
        jButton8.setText("Copiar [ctrl + c]");
        jButton8.setBorderPainted(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton8.setPreferredSize(new java.awt.Dimension(115, 70));
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setMnemonic(KeyEvent.VK_C);

        jButton11.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/32/Paste-icon.png"))); // NOI18N
        jButton11.setText("Colar [ctrl + v]");
        jButton11.setBorderPainted(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton11.setMinimumSize(new java.awt.Dimension(108, 68));
        jButton11.setPreferredSize(new java.awt.Dimension(130, 70));
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setMnemonic(KeyEvent.VK_P);

        jButton10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/32/cut-icon.png"))); // NOI18N
        jButton10.setText("Recortar [ctrl + x]");
        jButton10.setBorderPainted(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton10.setMinimumSize(new java.awt.Dimension(120, 68));
        jButton10.setPreferredSize(new java.awt.Dimension(135, 70));
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setMnemonic(KeyEvent.VK_T);

        jButton13.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/32/compile-icon.png"))); // NOI18N
        jButton13.setText("Compilar [F9]");
        jButton13.setBorderPainted(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton13.setPreferredSize(new java.awt.Dimension(108, 70));
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);

        jButton12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/32/group-icon.png"))); // NOI18N
        jButton12.setText("Equipe [F1]");
        jButton12.setBorderPainted(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButton12.setMaximumSize(new java.awt.Dimension(80, 66));
        jButton12.setMinimumSize(new java.awt.Dimension(80, 66));
        jButton12.setPreferredSize(new java.awt.Dimension(108, 70));
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);

        Rolagem2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Rolagem2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        Rolagem2.setMinimumSize(new java.awt.Dimension(900, 100));

        AreaMensagens.setColumns(20);
        AreaMensagens.setFont(new Font("monospaced", Font.PLAIN, 14));
        AreaMensagens.setRows(5);
        AreaMensagens.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AreaMensagens.setFocusable(false);
        AreaMensagens.setMinimumSize(new java.awt.Dimension(900, 100));
        Rolagem2.setViewportView(AreaMensagens);

        Painel2.setMinimumSize(new java.awt.Dimension(900, 30));

        AreaStatus.setEditable(false);
        AreaStatus.setColumns(20);
        AreaStatus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AreaStatus.setRows(5);
        AreaStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AreaStatus.setFocusable(false);
        AreaStatus.setMinimumSize(new java.awt.Dimension(900, 30));

        javax.swing.GroupLayout Painel2Layout = new javax.swing.GroupLayout(Painel2);
        Painel2.setLayout(Painel2Layout);
        Painel2Layout.setHorizontalGroup(
            Painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(AreaStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        Painel2Layout.setVerticalGroup(
            Painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AreaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Rolagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Rolagem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Painel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Rolagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(Rolagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Painel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (AreaTexto.getText().isEmpty()
                | AreaTexto.getText().matches("[\n \t  ]*")) {
            AreaMensagens.setText("nenhum programa para compilar");
        } else {
            Lexico lexico = new Lexico();

            lexico.setInput(AreaTexto.getText());
            String mensagem = "Linha     Classe                              Lexema                      \n";
            char[] texto = AreaTexto.getText().toCharArray();

            try {
                Token t = null;
                while ((t = lexico.nextToken()) != null) {

                    //detecta linha
                    int linha = 1;
                    int trava = t.getPosition();
                    for (int i = 0; i < trava; i++) {
                        if (texto[i] == '\n') {
                            linha++;
                        }
                    }

                    //Monta string com espaços certos
                    String linhastr = Integer.toString(linha);

                    for (int i = linhastr.length(); i < 10; i++) {
                        linhastr += " ";
                    }
                    mensagem += linhastr;

                    //Classe
                    String classe = Integer.toString(t.getId());

                    String classestr;
                    if (Classes.get(classe).getCodigo()[1] != null) {
                        classestr = "símbolo especial";
                    } else {
                        if (Integer.parseInt(Classes.get(classe).getCodigo()[0]) <= 7) {
                            classestr = Classes.get(classe).toString();
                            classestr = classestr.replace("_", " ");
                        } else {
                            classestr = "palavra reservada";
                        }

                    }

                    for (int i = classestr.length(); i < 36; i++) {
                        classestr += " ";
                    }

                    mensagem += classestr;

                    //Lexema
                    String lexemastr = t.getLexeme();
                    for (int i = lexemastr.length(); i < 22; i++) {
                        lexemastr += " ";
                    }

                    mensagem += lexemastr + "\n";

                }
                mensagem += "\nPrograma compilado com sucesso";
                AreaMensagens.setText(mensagem);

            } catch (LexicalError e) {

                int linha = 1;
                int trava = e.getPosition();
                for (int i = 0; i < trava; i++) {
                    if (texto[i] == '\n') {
                        linha++;
                    }
                }

                String mensagemErro = "Erro na linha " + linha + " - ";

                if (e.getMessage().equals("símbolo inválido")) {
                    AreaMensagens.setText(mensagemErro + texto[e.getPosition()] + " " + e.getMessage());
                } else {
                    AreaMensagens.setText(mensagemErro + e.getMessage());
                }
            }

        }

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        AreaMensagens.setText("Desenvolvedores: Henrique José Wilbert\n"
                + "e Célio Rodrigues Júnior");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (AreaStatus.getText().equals("")) {
            JFileChooser chooser = new JFileChooser();
            int opc = chooser.showSaveDialog(null);
            if (opc == JFileChooser.APPROVE_OPTION) {
                try {
                    String nome = chooser.getSelectedFile().toString();
                    FileWriter fw;
                    if (nome.endsWith(".txt")) {
                        fw = new FileWriter(nome);
                    } else {
                        fw = new FileWriter(nome + ".txt");
                    }

                    fw.write(AreaTexto.getText());
                    fw.close();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                AreaMensagens.setText("");
                AreaStatus.setText(chooser.getSelectedFile().getPath());
            }
        } else {
            try {
                String nome = AreaStatus.getText();
                FileWriter fw;
                if (nome.endsWith(".txt")) {
                    fw = new FileWriter(AreaStatus.getText());
                } else {
                    fw = new FileWriter(AreaStatus.getText() + ".txt");
                }
                fw.write(AreaTexto.getText());
                fw.close();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            AreaMensagens.setText("");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        AreaTexto.getTransferHandler();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Arquivo de Texto", "txt");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            String caminho = chooser.getSelectedFile().getPath();
            String lista = CarregadorArquivos.carrega(caminho);
            AreaTexto.setText(lista);
            AreaTexto.setCaretPosition(0);
            AreaMensagens.setText("");
            AreaStatus.setText(caminho);
            pack();
        }
        if (returnVal == JFileChooser.CANCEL_OPTION) {

        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AreaTexto.setText("");
        AreaMensagens.setText("");
        AreaStatus.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Interface a = new Interface();

                a.setVisible(true);
                a.getContentPane();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaMensagens;
    private javax.swing.JTextArea AreaStatus;
    private javax.swing.JTextArea AreaTexto;
    private javax.swing.JPanel Painel2;
    private javax.swing.JScrollPane Rolagem1;
    private javax.swing.JScrollPane Rolagem2;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
